### ISSUE TITLE
python3 rasa_nlu_model.py failure

### ISSUE THREAD

**Issue by BobCN2017** [rahul051296/small-talk-rasa#1]
D:\python3\python36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "rasa_nlu_model.py", line 14, in <module>
    train_nlu('./data/nlu', './config.yml', './models/nlu')
  File "rasa_nlu_model.py", line 8, in train_nlu
    trainer = Trainer(config.load(configuration))
  File "D:\python3\python36\lib\site-packages\rasa_nlu\model.py", line 149, in __init__
    self.pipeline = self._build_pipeline(cfg, component_builder)
  File "D:\python3\python36\lib\site-packages\rasa_nlu\model.py", line 160, in _build_pipeline
    component_name, cfg)
  File "D:\python3\python36\lib\site-packages\rasa_nlu\components.py", line 420, in create_component
    cfg)
  File "D:\python3\python36\lib\site-packages\rasa_nlu\registry.py", line 140, in create_component_by_name
    return component_clz.create(config)
  File "D:\python3\python36\lib\site-packages\rasa_nlu\utils\spacy_utils.py", line 73, in create
    nlp = spacy.load(spacy_model_name, parser=False)
  File "D:\python3\python36\lib\site-packages\spacy\__init__.py", line 15, in load
    return util.load_model(name, **overrides)
  File "D:\python3\python36\lib\site-packages\spacy\util.py", line 119, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
can you hlep me to fix it.
thank you very much!

**Comment by BobCN2017** [comment]
python3 -m spacy download en_core_web_md
python3 -m spacy link en_core_web_md en
I find this in https://core.rasa.com/tutorial_basics.html
It solved.
